dataset:
  type: "hilti"
  path: "evaluation/hilti"
  patches:
    start: 0
    end: 29
    step: 10
    iterations: 1
pipeline:
  grid:
    voxel_edge_length: 8
  subdividers:
    size: 1
  segmenters:
    ransac:
      threshold: 0.01
      initial_points: 6
      iterations: 1000
  backend:
    type: "eigen_factor"
    parameters:
      iterations_number: 5000
      robust_type: QUADRATIC
  output: "output/hilti"
debug: false