dataset:
  type: "hilti"
  path: "datasets/hilti/Drone"
  patches:
    start: 0
    end: 895
    step: 50
    iterations: 2
pipeline:
  grid:
    voxel_edge_length: 8
  subdividers:
    size: 1
  segmenters:
    ransac:
      threshold: 0.01
      initial_points: 6
      iterations: 1000
  backend:
    type: "eigen_factor"
    parameters:
      iterations_number: 5000
      robust_type: QUADRATIC
  output: "output/hilti/Drone"
debug: false