dataset:
  path: "hilti/basement1"
  patches:
    start: 400
    end: 405
    step: 5
    iterations: 1
  output: "output/hilti/basement1"
undistortion:
  segments: 1000
pipeline:
  iterations: 1
  grid:
    voxel_edge_length: 8
  subdividers:
    size: 1
  segmenters:
    ransac:
      threshold: 0.01
      initial_points: 6
      iterations: 300
  backend:
    type: "eigen_factor"
    parameters:
      iterations_number: 5000
      robust_type: QUADRATIC
debug: false