dataset:
  type: "kitti"
  path: "evaluation/kitti"
  patches:
    start: 0
    end: 100
    step: 10
    iterations: 1
pipeline:
  grid:
    voxel_edge_length: 16
  subdividers:
    size: 2
  segmenters:
    ransac:
      threshold: 0.01
      initial_points: 6
      iterations: 5000
    cape:
      correlation: 300
  backend:
    type: "eigen_factor"
    parameters:
      iterations_number: 5000
      robust_type: HUBER
  output: "output/kitti"
debug: true